---
  - name: Check if cudo-miner signing exists
    stat:
      path: /etc/apt/trusted.gpg.d/cudo.asc
    register: stat_result
        
  - name: Add cudo-miner signing
    become: yes
    shell: wget -O /etc/apt/trusted.gpg.d/cudo.asc https://download.cudo.org/keys/pgp/apt.asc 
    when: not stat_result.stat.exists

  - name: Add cudo-miner repostiory
    become: yes
    shell: echo 'deb [arch=amd64] https://download.cudo.org/repo/apt/ stable main' | tee /etc/apt/sources.list.d/cudo.list
    when: not stat_result.stat.exists

  - name: Install apt packages
    become: yes
    ignore_errors: true
    apt:
      pkg:
      - fzf
      - htop
      - neovim
      - tmux
      - tree
      - zsh
      - ranger
      - ripgrep
      - fd-find
      - universal-ctags
      - borgbackup
      - yadm
      - cudo-miner-core
      - cudo-miner-service
      - cudo-miner-cli
      - cudo-miner-headless
      - cudo-miner #This depends Xorg and minimum gnome desktop. However without, cudo-miner does not list gpu's
      - wget
      - build-essential 
      - cmake 
      - git 
      - libuv1-dev 
      - libssl-dev
      - libhwloc-dev 
      - libmicrohttpd-dev 
      - lm-sensors  
      - opencl-amdgpu-pro-dev
      - clinfo
      - zsh-syntax-highlighting
      - zsh-autosuggestions
  - name: Remove apt packages
    become: yes
    apt:
      name:
        ["something", "purge" ]
      state: absent

  - name: Remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes
  
  - name: Test if oh-my-zsh is present.
      stat:
        path: "{{ local_home }}/.oh-my-zsh"
      register: ohmyzsh

  - name: Install "oh-my-zsh"
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when: not ohmyzsh.stat.exists
