---
# populate a fresh Pop!_os instance
- hosts: 127.0.0.1
  connection: local
  vars:
    local_user: "{{ ansible_user_id }}"
    local_home: "{{ lookup('env','HOME') }}"
    region_loc: "us_US.UTF-8"
    new_hostname: "miner-{{ ansible_date_time.iso8601_basic }}"
    
  roles:
    - { role: nvidia, tags: "nvdia" }
    - { role: radeon, tags: "cudo" }
    - { role: cudo, tags: "radeon" }

  tasks:
    - name: Set hostname of the machine
      become: yes
      shell: "echo '{{ new_hostname }}' > '/etc/hostname'"


      
