---
# populate a fresh Pop!_os instance
- hosts: 127.0.0.1
  connection: local
  vars:
    local_user: "{{ ansible_user_id }}"
    local_home: "{{ lookup('env','HOME') }}"
    region_loc: "us_US.UTF-8"
    new_hostname: "miner-{{ ansible_date_time.iso8601_basic }}"
    
-debug: var=new_hostname    
  roles:
    - { role: nvidia, tags: "nvdia" }
    - { role: radeon, tags: "cudo" }
    - { role: cudo, tags: "radeon" }

  tasks:
    - name: Set hostname of the machine
      become: yes
      shell: "echo '{{ new_hostname }}' > '/etc/hostname'"

    - name: Create a directory if it does not exist
      file:
        path: "{{ local_home }}/amd-driver"
      state: directory

    - name: Test if oh-my-zsh is present.
      stat:
        path: "{{ local_home }}/.oh-my-zsh"
      register: ohmyzsh

    - name: Install "oh-my-zsh"
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not ohmyzsh.stat.exists
      
