--

- debug: var=local_user
- debug: var=local_home

- set_fact:
    tempdir: /var/tmp/pline_fonts
    download: "{{ local_home }}/Download"
    driver: amdgpu-pro-20.20-1098277-ubuntu-20.04.tar.xz
    drivers_dir: "{{ local_home }}/amd-driver"

- debug: var=drivers_dir

- name: Checking if installer exists
  stat:
    path: "{{ drivers_dir }}/amdgpu-pro-install"
  register: driverexists

- debug: var=driverexists.stat.exists

- name: get driver
  shell:  "wget -N https://drivers.amd.com/drivers/linux/{{ driver }} --referer https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-20 -P {{ local_home }}"
  when: driverexists.stat.exists == false

- name: Extract
  shell: "tar -Jxvf {{ local_home }}/{{ driver }} -C {{ drivers_dir }} --strip-components=1"
  when: driverexists.stat.exists == false

- name: Install amdgpu-pro headless drivers (ubuntu-server 20.04)
  become: yes
  shell: "{{ drivers_dir }}/amdgpu-pro-install -y --opencl=pal,legacy,rocm --headless"
  when: driverexists.stat.exists == false
# TODO Write these to /etc/default/grub if not exists
# GRUB_CMDLINE_LINUX_DEFAULT="text amdgpu.ppfeaturemask=0xffffffff"
# sudo update-grub && sudo update-grub2 && sudo update-initramfs -u -k all

